# We have a conf and classes directory, but we have classes that should
# override those in oe-core, so prepend to BBPATH
BBPATH =. "${LAYERDIR}:"

# We have a recipes directory, add to BBFILES
BBFILES += "${LAYERDIR}/recipes*/*/*.bb ${LAYERDIR}/recipes*/*/*.bbappend"

BBFILE_COLLECTIONS += "lts-mixin-u-boot"
BBFILE_PATTERN_lts-mixin-u-boot := "^${LAYERDIR}/"
BBFILE_PRIORITY_lts-mixin-u-boot = "6"

LAYERSERIES_COMPAT_lts-mixin-u-boot = "scarthgap"

LAYERDEPENDS_lts-mixin-u-boot = "core"
